name: Superpack Native Library Extraction
on: [push]
jobs:
  initialize-environment:
    runs-on: macos-11
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@master
        with:
          python-version: '3.7'

      - name: Install apktool
        run: brew install apktool

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Install and extract binaries
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: /bin/sh ./duper-extract.sh

      - name: 'Upload Arm64 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp-Arm64-libraries'
          path: libs.spo.arm64.zip
          retention-days: 1
      - name: 'upload apk files'
        uses: actions/upload-artifacts@v3
        with:
          name: 'whatsapp-apk-files'
          path: com.whatsapp.zip
          retention-days: 1

      - name: 'Upload x86 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp-x86-libraries'
          path: libs.spo.x86.zip
          retention-days: 1

      - name: 'Upload x86_64 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp-x86_64-libraries'
          path: libs.spo.x86_64.zip
          retention-days: 1

      - name: 'Upload armeabi-v7a Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp-armeabi-v7a-libraries'
          path: libs.spo.armeabi-v7a.zip
          retention-days: 1
