name: Superpack Native Library Extraction
run-name: Duperpack is extracting libraries!
on: [push]
jobs:
  initialize-environment:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

       - uses: actions/setup-python@master
         with:
           python-version: '3.7'

       - name: Install awsebcli
         run: pip install -U awsebcli

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29

      - name: test connectivity
	run: adb devices
