name: Superpack Native Library Extraction
run-name: Duperpack is extracting libraries!
on: [push]
jobs:
  initialize-environment:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@master
        with:
          python-version: '3.7'

      - name: Install apktool
        run: |
          brew update
          brew install apktool

      - name: Create emulator and install frida-server
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true

      - name: install WhatsApp
        run: adb install WhatsApp.apk

      - name: Start WhatsApp
        run: adb shell am start -n com.whatsapp/.Main && adb root

      - name: Pull standard libs
        run: adb pull /data/data/com.whatsapp/files/decompressed/libs.spk.zst/ . && mv libs.spk.zst libs.spk.zst.arm64

      - name: Uninstall WhatsApp
        run: adb uninstall com.whatsapp

      - name: Unpack WhatsApp
        run: apktool d -rs WhatsApp.apk

      - name: List directory and move
        run: ls ./WhatsApp && mv WhatsApp/assets/compressed/x86/libs.spk.zst WhatsApp/assets/compressed/arm64-v8a/.
      
      - name: Rebuild WhatsApp
        run: apktool b WhatsApp

      - name: Sign new APK
        run: java -jar ./uber-apk-signer-1.3.0.jar -a ./WhatsApp/dist/WhatsApp.apk && ls ./WhatsApp/dist/
