name: Superpack Native Library Extraction
run-name: Duperpack is extracting libraries!
on: [push]
jobs:
  initialize-environment:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install frida-tools
	run: pip3 install frida-tools

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29

      - name: test connectivity
	run: adb devices
