name: Superpack Native Library Extraction
run-name: Duperpack is extracting libraries!
on: [push]
jobs:
  initialize-environment:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@master
        with:
          python-version: '3.7'

      - name: Install apktool
        run: brew install apktool

      - name: Create emulator and install frida-server
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: bash ./duper-extract.sh

      - name: 'Upload Arm64 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp Arm64 Libraries'
          path: libs.spk.zst.arm64.zip
          retention-days: 1

      - name: 'Upload x86 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp x86 Libraries'
          path: libs.spk.zst.x86.zip
          retention-days: 1

      - name: 'Upload x86_64 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp x86_64 Libraries'
          path: libs.spk.zst.x86_64.zip
          retention-days: 1

      - name: 'Upload armeabi-v7a Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'WhatsApp armeabi-v7a Libraries'
          path: libs.spk.zst.armeabi-v7a.zip
          retention-days: 1
